# Generated by Django 5.2.17 on 2026-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='refresh_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
